
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gojxbfefcqjrrrzjdtfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvanhiZmVmY3FqcnJyempkdGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTIyMjMsImV4cCI6MjA1ODQ2ODIyM30.i1IHA4LZB7r80VN0pZVvT7BNtHuXUqBu_Wy0nkXeqB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);

// For debugging purposes only
console.log('Supabase client initialized with URL:', SUPABASE_URL);
